name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.2
        envkey_REACT_APP_GMAP_JS_API_KEY: ${{ secrets.GMAP_JS_API_KEY }}
        envkey_REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        envkey_REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        envkey_REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        envkey_REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        envkey_REACT_APP_UUID_NAMESPACE: ${{ secrets.UUID_NAMESPACE }}
      - name: install yarn dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
      - name: create production build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: deploy production build to firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LETS_PLAN_FIREBASE }}'
          channelId: live
          projectId: lets-plan-firebase
